### ISSUE TITLE
socket.io connection only works with localhost

### ISSUE THREAD

**Issue by dsl400** [arondn2/loopback4-example-websocket-app#16]
Thanks for the upload, it took me a while to find it :)
it has a quirk it will only accept socket.io connection on localhost
the server accepts http requests on all interfaces (127.0.0.1 and 192.168.1.x) but sockets only work if connection is made to ws://localhost:3000

**Comment by dsl400** [comment]
theoretically the rest and ws are on the same port but not on the same interface 
adding host address to websocket options eg:

`rest: {
      port,
      host: '0.0.0.0'
    },
    websocket: {
            port,
            host: '0.0.0.0'
    }`
in file [index.ts](https://github.com/alexkander/loopback4-example-websocket-app/blob/master/src/index.ts) will result in error
`Cannot start the application. Error: listen EADDRINUSE: address already in use 0.0.0.0:3000
    at Server.setupListenHandle [as _listen2] (net.js:1320:16)
    at listenInCluster (net.js:1368:12)
    at doListen (net.js:1505:7)
    at processTicksAndRejections (internal/process/task_queues.js:83:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 3000
}`
the question remains .... how to bind socket.io to the same interface:port as rest ?

**Comment by dsl400** [comment]
placing the host only in websocket options will make sockets be accesible via all interfaces
`rest: { port}, websocket: { port, host: '0.0.0.0' }`
